// SPDX-FileCopyrightText: 2026 hmgle
// SPDX-License-Identifier: GPL-3.0-only

use std::collections::{BTreeMap, BTreeSet};
use std::env;
use std::fs;
use std::path::PathBuf;

const ROLES: [&str; 3] = ["data_plane", "namespace_init", "supervisor"];
const ARCHITECTURES: [&str; 2] = ["aarch64", "x86_64"];

fn main() {
    println!("cargo:rerun-if-changed=syscalls.toml");
    let manifest = fs::read_to_string("syscalls.toml").expect("read syscalls.toml");
    let target_arch = env::var("CARGO_CFG_TARGET_ARCH").expect("CARGO_CFG_TARGET_ARCH");
    if !ARCHITECTURES.contains(&target_arch.as_str()) {
        panic!("unsupported seccomp target architecture {target_arch:?}");
    }
    let parsed = parse_manifest(&manifest);
    let aliases = parsed
        .aliases
        .get(&target_arch)
        .expect("target alias table");
    let mut output = String::from("// @generated by build.rs from syscalls.toml.\n");
    for role in ROLES {
        let mut syscalls = parsed.roles.get(role).expect("role syscall table").clone();
        if let Some(architecture_roles) = parsed.architecture_roles.get(&target_arch)
            && let Some(architecture_syscalls) = architecture_roles.get(role)
        {
            syscalls.extend(architecture_syscalls.iter().cloned());
        }
        output.push_str(&format!(
            "pub const {}: &[libc::c_long] = &[\n",
            role.to_ascii_uppercase()
        ));
        for syscall in syscalls {
            let resolved = aliases
                .get(&syscall)
                .map_or(syscall.as_str(), String::as_str);
            output.push_str(&format!("    libc::SYS_{resolved},\n"));
        }
        output.push_str("];\n");
    }
    let out_dir = PathBuf::from(env::var_os("OUT_DIR").expect("OUT_DIR"));
    fs::write(out_dir.join("seccomp_profiles.rs"), output)
        .expect("write generated seccomp profiles");
}

#[derive(Default)]
struct Manifest {
    aliases: BTreeMap<String, BTreeMap<String, String>>,
    architecture_roles: BTreeMap<String, BTreeMap<String, BTreeSet<String>>>,
    roles: BTreeMap<String, BTreeSet<String>>,
}

fn parse_manifest(contents: &str) -> Manifest {
    enum Section {
        None,
        Aliases(String),
        ArchitectureRole(String, String),
        Role(String),
    }

    let mut manifest = Manifest::default();
    let mut section = Section::None;
    for (index, raw) in contents.lines().enumerate() {
        let line_number = index + 1;
        let line = raw.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        if line.starts_with('[') && line.ends_with(']') {
            let fields = line[1..line.len() - 1].split('.').collect::<Vec<_>>();
            section = match fields.as_slice() {
                ["aliases", architecture] if ARCHITECTURES.contains(architecture) => {
                    Section::Aliases((*architecture).to_owned())
                }
                ["role", role, feature] if ROLES.contains(role) && valid_identifier(feature) => {
                    Section::Role((*role).to_owned())
                }
                ["arch", architecture, role, feature]
                    if ARCHITECTURES.contains(architecture)
                        && ROLES.contains(role)
                        && valid_identifier(feature) =>
                {
                    Section::ArchitectureRole((*architecture).to_owned(), (*role).to_owned())
                }
                _ => panic!("invalid syscalls.toml section at line {line_number}: {line}"),
            };
            continue;
        }
        let (key, value) = line
            .split_once('=')
            .unwrap_or_else(|| panic!("missing '=' at syscalls.toml line {line_number}"));
        let key = key.trim();
        let value = value.trim();
        assert!(
            valid_identifier(key),
            "invalid syscall name at syscalls.toml line {line_number}"
        );
        assert!(
            value.len() >= 2 && value.starts_with('"') && value.ends_with('"'),
            "value must be a non-empty quoted string at syscalls.toml line {line_number}"
        );
        let value = &value[1..value.len() - 1];
        assert!(
            !value.is_empty() && !value.contains('"'),
            "invalid value at syscalls.toml line {line_number}"
        );
        match &section {
            Section::Aliases(architecture) => {
                let replaced = manifest
                    .aliases
                    .entry(architecture.clone())
                    .or_default()
                    .insert(key.to_owned(), value.to_owned());
                assert!(
                    replaced.is_none(),
                    "duplicate alias at syscalls.toml line {line_number}"
                );
            }
            Section::Role(role) => {
                manifest
                    .roles
                    .entry(role.clone())
                    .or_default()
                    .insert(key.to_owned());
            }
            Section::ArchitectureRole(architecture, role) => {
                manifest
                    .architecture_roles
                    .entry(architecture.clone())
                    .or_default()
                    .entry(role.clone())
                    .or_default()
                    .insert(key.to_owned());
            }
            Section::None => panic!("entry before section at syscalls.toml line {line_number}"),
        }
    }
    for architecture in ARCHITECTURES {
        assert!(
            manifest.aliases.contains_key(architecture),
            "missing alias table for {architecture}"
        );
    }
    for role in ROLES {
        assert!(
            manifest
                .roles
                .get(role)
                .is_some_and(|entries| !entries.is_empty()),
            "missing syscall profile for {role}"
        );
    }
    manifest
}

fn valid_identifier(value: &str) -> bool {
    !value.is_empty()
        && value
            .bytes()
            .all(|byte| byte.is_ascii_lowercase() || byte.is_ascii_digit() || byte == b'_')
}
