[package]
name = "yayatht-sys"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
build = "build.rs"

[dependencies]
libc.workspace = true
linux-raw-sys.workspace = true
rustix.workspace = true
thiserror.workspace = true

[lints]
workspace = true
