[package]
name = "yayatht-tcp-adapter"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
description = "TCP flow state, sequencing, and timers for yayatht"
license.workspace = true
homepage.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]
arrayvec.workspace = true
thiserror.workspace = true
yayatht-packet = { version = "=0.1.0", path = "../packet" }

[lints]
workspace = true
